version: '3'
services:
  db:
    image: mysql
    container_name: docker-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./docker/data:/docker-entrypoint-initdb.d
      - ./docker/config:/etc/mysql/conf.d
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
